Implement Platform::parse_types_from_source
Vector35/binaryninja-api pull request #2322
Opened 2021-03-15 16:36 UTC by joshwatson

2021-03-19 02:10 UTC, KyleMiles requested changes
And pls squash

2021-03-19 02:10 UTC, KyleMiles commented on rust/src/platform.rs
> +            include_dirs.push(d.as_ptr() as *const i8);
`as *const i8` -> `as _`

2021-03-19 18:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Vector35/binaryninja-api?pullRequest=2322) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Vector35/binaryninja-api?pullRequest=2322) before we can accept your contribution.<br/>**1** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: joshwatson<br/>:x: Brian Knudson<br/>:x: plafosse<br/>:x: KyleMiles<br/>:x: D0ntPanic<br/>:x: CouleeApps<br/><hr/>**Brian Knudson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Vector35/binaryninja-api?pullRequest=2322) it.</sub>

2021-03-19 21:28 UTC, joshwatson commented
ok I think I have squashed and fixed issues 😃

2021-03-19 22:46 UTC, KyleMiles commented
What's there now seems like the original version

2021-03-19 22:48 UTC, KyleMiles commented
Ah, that would be because GitHub had a big red "Refresh" button at the top.

2021-03-19 22:50 UTC, KyleMiles commented
Okay, only the `.as_ref() as *const [u8] as *const i8` -> `.as_ref().as_ptr() as _` remains.

2021-03-19 22:56 UTC, joshwatson commented on rust/src/platform.rs
> +                src.as_ref() as *const [u8] as *const i8,
doh I completely missed those two

2021-03-19 23:20 UTC, KyleMiles requested changes
Sorry, this should be the last one.  Beware the `i8`!

2021-03-19 23:20 UTC, KyleMiles commented on rust/src/platform.rs
> +        let mut error_string: *mut i8 = ptr::null_mut();
This actually needs to be a `raw: *mut raw::c_char` per `string::BnString::raw`, and then you can take `BnString::from_raw(...)`; the error strings are left for us to deallocate, plus we need to account for the ARM char difference.

Alternatively, we could just not handle the errors and the fifth argument to `BNParseTypesFromSource` can be a nullptr.  I'm okay with either solution.

2021-03-22 17:02 UTC, KyleMiles approved these changes

2021-03-22 17:04 UTC, merged