Add API to get all SSA versions of a variable
Vector35/binaryninja-api pull request #4548
Opened 2023-08-05 04:26 UTC by emesare

Added a missing helper for both `MediumLevelILFunction` and `HighLevelILFunction` classes to get a list of all SSA versions of a variable.

2023-08-05 04:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Vector35/binaryninja-api?pullRequest=4548) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Vector35/binaryninja-api?pullRequest=4548) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Vector35/binaryninja-api?pullRequest=4548) it.</sub>

2023-08-09 09:33 UTC, xusheng6 requested changes
Nice catch and thx for the contribution!

There is one little change needed before I can merge this: The versions returned by the core API are allocated in the core (https://github.com/Vector35/binaryninja-api/pull/4548/files#diff-8ac95093418e4830504276ed52f586164037fd3bd25b24634199cda30dd7f18fR347), and the current implementation is causing memory leak because the API side does not free the array. You need to add a call to free it as we do here: https://github.com/Vector35/binaryninja-api/blob/7598688466960427890036590239565364310171/function.cpp#L1412. (You can ignore the name `BNFreeILInstructionList`, it essentially just frees an size_t array via its pointer)

If you are not sure about what I mean, you can let me know and I can take over the job and commit it directly.

2023-08-09 19:33 UTC, emesare commented
> . (You can ignore the name `BNFreeILInstructionList`, it essentially just frees an size_t array via its pointer)

I was unsure about if that was only for instruction lists, thank you for the clarification!

2023-08-10 03:58 UTC, xusheng6 commented
Merged into b6ce48c4f5be4cd43482e1ff762e088fd11b7227

2023-08-10 03:58 UTC, closed without merging