Implement functions from python Function
Vector35/binaryninja-api pull request #5378
Opened 2024-05-08 12:07 UTC by rbran

2024-05-09 13:06 UTC, rbran commented
Tests being written at: https://github.com/rbran/binaryninja-test mostly on [mlil_vars](https://github.com/rbran/binaryninja-test/tree/main/mlil_vars)

2024-05-10 16:25 UTC, KyleMiles commented
At least for basic blocks, the UI does the following with highlight colors:
```
QColor blockColor = m_render.getHighlightColor(line.block->GetBasicBlockHighlight());
blockColor.setAlpha((blockColor.alpha() * 80) / 255);
if (blockColor.alpha() != 0)
{
	p.setPen(QColor(0, 0, 0, 0));
	p.setBrush(blockColor);
	p.drawRect(xoffset, 2 + (y * charHeight), viewportWidth, charHeight);
}
```

2024-05-11 10:48 UTC, rbran commented
I guess it all depends on the `getHighlightColor`, just in case I added an alpha value for [HighlightColor::NoHighlightColor](https://github.com/Vector35/binaryninja-api/pull/5378/commits/26619bf4640cb1626a459fc813f949348a21ce91)

2024-05-20 16:32 UTC, KyleMiles requested changes
This is tremendous! Thank you for your work. Just a couple changes requested:
 - [ ] Rename `VariableDefinitions`
 - [ ] Finish implementing `PossibleValueSet` (or correct me if I'm wrong)

2024-05-20 16:32 UTC, KyleMiles commented on rust/src/types.rs
> +            ImportedAddressValue => Self::ImportedAddressValue,
Unfinished? These should all have values. `NotInSetOfValues` has the same inner value as `InSetOfValues`

2024-05-20 16:32 UTC, KyleMiles commented on rust/src/types.rs
> +            BNHighlightStandardColor::NoHighlightColor => return None,
Clever translation to Rust-isms. I like this!

2024-05-20 17:09 UTC, rbran commented on rust/src/mlil/function.rs
> +    pub fn get_var_definitions<'a>(&'a self, var: &Variable) -> VariableDefinitions<'a> {
Renamed

2024-05-20 19:44 UTC, merged